import db from './connection.js';
import bcrypt from 'bcryptjs';
import { v4 as uuidv4 } from 'uuid';
const now = new Date().toISOString();
const seedData = async () => {
  const deptHrId = uuidv4();
  const deptItId = uuidv4();
  const deptFinanceId = uuidv4();
  db.pragma('foreign_keys = OFF');
  db.exec(`DELETE FROM auditLogs`);
  db.exec(`DELETE FROM notifications`);
  db.exec(`DELETE FROM calendarEvents`);
  db.exec(`DELETE FROM leaveBalances`);
  db.exec(`DELETE FROM leaveRequests`);
  db.exec(`DELETE FROM attendance`);
  db.exec(`DELETE FROM salaries`);
  db.exec(`DELETE FROM contracts`);
  db.exec(`DELETE FROM employeeAllowances`);
  db.exec(`DELETE FROM insurance`);
  db.exec(`DELETE FROM users`);
  db.exec(`DELETE FROM employees`);
  db.exec(`DELETE FROM positions`);
  db.exec(`DELETE FROM departments`);
  db.exec(`DELETE FROM leaveTypes`);
  db.exec(`DELETE FROM allowances`);
  db.exec(`DELETE FROM holidays`);
  const posHrManagerId = uuidv4();
  const posHrStaffId = uuidv4();
  const posItManagerId = uuidv4();
  const posItDevId = uuidv4();
  const posFinanceManagerId = uuidv4();
  const posAccountantId = uuidv4();
  db.prepare(`INSERT INTO departments (id, name, code, parentDepartmentId, managerId, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?)`).run(deptHrId, 'Phòng Nhân Sự', 'HR', null, null, now, now);
  db.prepare(`INSERT INTO departments (id, name, code, parentDepartmentId, managerId, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?)`).run(deptItId, 'Phòng Công Nghệ', 'IT', null, null, now, now);
  db.prepare(`INSERT INTO departments (id, name, code, parentDepartmentId, managerId, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?)`).run(deptFinanceId, 'Phòng Tài Chính', 'FIN', null, null, now, now);
  db.prepare(`INSERT INTO positions (id, name, code, level, departmentId, baseSalary, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`).run(posHrManagerId, 'Trưởng Phòng Nhân Sự', 'HR-MGR', 2, deptHrId, 30000000, now, now);
  db.prepare(`INSERT INTO positions (id, name, code, level, departmentId, baseSalary, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`).run(posHrStaffId, 'Nhân Viên Nhân Sự', 'HR-STAFF', 3, deptHrId, 15000000, now, now);
  db.prepare(`INSERT INTO positions (id, name, code, level, departmentId, baseSalary, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`).run(posItManagerId, 'Trưởng Phòng IT', 'IT-MGR', 2, deptItId, 35000000, now, now);
  db.prepare(`INSERT INTO positions (id, name, code, level, departmentId, baseSalary, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`).run(posItDevId, 'Lập Trình Viên', 'IT-DEV', 3, deptItId, 20000000, now, now);
  db.prepare(`INSERT INTO positions (id, name, code, level, departmentId, baseSalary, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`).run(posFinanceManagerId, 'Trưởng Phòng Tài Chính', 'FIN-MGR', 2, deptFinanceId, 32000000, now, now);
  db.prepare(`INSERT INTO positions (id, name, code, level, departmentId, baseSalary, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`).run(posAccountantId, 'Kế Toán Viên', 'FIN-ACC', 3, deptFinanceId, 18000000, now, now);
  const empHrroId = uuidv4();
  const empHrManagerId = uuidv4();
  const empItManagerId = uuidv4();
  const empDev1Id = uuidv4();
  db.prepare(`INSERT INTO employees (id, employeeCode, firstName, lastName, fullName, email, phone, personalEmail, dateOfBirth, gender, nationalId, nationalIdDate, nationalIdPlace, taxCode, bankAccount, bankName, bankBranch, permanentAddress, currentAddress, positionId, departmentId, managerId, isManager, hireDate, terminationDate, employmentStatus, employmentType, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`).run(empHrroId, 'NV001', 'Minh', 'Nguyễn Văn', 'Nguyễn Văn Minh', 'minh.nguyen@company.com', '0901234567', 'minh.personal@gmail.com', '1985-05-15', 'male', '012345678901', '2020-01-15', 'Hà Nội', '8012345678', '0123456789', 'Vietcombank', 'Chi Nhánh Hà Nội', '123 Phố Huế, Hai Bà Trưng, Hà Nội', '456 Láng Hạ, Đống Đa, Hà Nội', posHrManagerId, deptHrId, null, 1, '2026-01-05', null, 'active', 'fullTime', now, now);
  db.prepare(`INSERT INTO employees (id, employeeCode, firstName, lastName, fullName, email, phone, personalEmail, dateOfBirth, gender, nationalId, nationalIdDate, nationalIdPlace, taxCode, bankAccount, bankName, bankBranch, permanentAddress, currentAddress, positionId, departmentId, managerId, isManager, hireDate, terminationDate, employmentStatus, employmentType, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`).run(empHrManagerId, 'NV002', 'Hương', 'Trần Thị', 'Trần Thị Hương', 'huong.tran@company.com', '0902345678', 'huong.personal@gmail.com', '1990-08-20', 'female', '012345678902', '2019-06-10', 'Hà Nội', '8012345679', '0123456790', 'Techcombank', 'Chi Nhánh Cầu Giấy', '789 Kim Mã, Ba Đình, Hà Nội', '321 Nguyễn Chí Thanh, Đống Đa, Hà Nội', posHrStaffId, deptHrId, empHrroId, 0, '2026-01-10', null, 'active', 'fullTime', now, now);
  db.prepare(`INSERT INTO employees (id, employeeCode, firstName, lastName, fullName, email, phone, personalEmail, dateOfBirth, gender, nationalId, nationalIdDate, nationalIdPlace, taxCode, bankAccount, bankName, bankBranch, permanentAddress, currentAddress, positionId, departmentId, managerId, isManager, hireDate, terminationDate, employmentStatus, employmentType, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`).run(empItManagerId, 'NV003', 'Đức', 'Lê Văn', 'Lê Văn Đức', 'duc.le@company.com', '0903456789', 'duc.personal@gmail.com', '1988-12-25', 'male', '012345678903', '2018-09-20', 'TP.HCM', '8012345680', '0123456791', 'BIDV', 'Chi Nhánh TP.HCM', '456 Lê Lợi, Quận 1, TP.HCM', '789 Nguyễn Huệ, Quận 1, TP.HCM', posItManagerId, deptItId, null, 1, '2026-01-15', null, 'active', 'fullTime', now, now);
  db.prepare(`INSERT INTO employees (id, employeeCode, firstName, lastName, fullName, email, phone, personalEmail, dateOfBirth, gender, nationalId, nationalIdDate, nationalIdPlace, taxCode, bankAccount, bankName, bankBranch, permanentAddress, currentAddress, positionId, departmentId, managerId, isManager, hireDate, terminationDate, employmentStatus, employmentType, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`).run(empDev1Id, 'NV004', 'An', 'Phạm Văn', 'Phạm Văn An', 'an.pham@company.com', '0904567890', 'an.personal@gmail.com', '1995-03-10', 'male', '012345678904', '2021-02-15', 'Đà Nẵng', '8012345681', '0123456792', 'ACB', 'Chi Nhánh Đà Nẵng', '123 Bạch Đằng, Hải Châu, Đà Nẵng', '456 Nguyễn Văn Linh, Hải Châu, Đà Nẵng', posItDevId, deptItId, empItManagerId, 0, '2026-01-20', null, 'active', 'fullTime', now, now);
  db.prepare(`UPDATE departments SET managerId = ? WHERE id = ?`).run(empHrroId, deptHrId);
  db.prepare(`UPDATE departments SET managerId = ? WHERE id = ?`).run(empItManagerId, deptItId);
  const userHrroId = uuidv4();
  const userHrManagerId = uuidv4();
  const userItManagerId = uuidv4();
  const userDev1Id = uuidv4();
  const passwordHash = await bcrypt.hash('password123', 10);
  db.prepare(`INSERT INTO users (id, email, passwordHash, role, employeeId, isActive, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`).run(userHrroId, 'minh.nguyen@company.com', passwordHash, 'hrro', empHrroId, 1, now, now);
  db.prepare(`INSERT INTO users (id, email, passwordHash, role, employeeId, isActive, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`).run(userHrManagerId, 'huong.tran@company.com', passwordHash, 'employee', empHrManagerId, 1, now, now);
  db.prepare(`INSERT INTO users (id, email, passwordHash, role, employeeId, isActive, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`).run(userItManagerId, 'duc.le@company.com', passwordHash, 'manager', empItManagerId, 1, now, now);
  db.prepare(`INSERT INTO users (id, email, passwordHash, role, employeeId, isActive, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`).run(userDev1Id, 'an.pham@company.com', passwordHash, 'employee', empDev1Id, 1, now, now);
  const leaveAnnualId = uuidv4();
  const leaveSickId = uuidv4();
  const leaveMaternityId = uuidv4();
  db.prepare(`INSERT INTO leaveTypes (id, name, code, paidLeave, maxDaysPerYear, description, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`).run(leaveAnnualId, 'Nghỉ Phép Năm', 'ANNUAL', 1, 12, 'Ngày nghỉ phép năm theo quy định', now, now);
  db.prepare(`INSERT INTO leaveTypes (id, name, code, paidLeave, maxDaysPerYear, description, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`).run(leaveSickId, 'Nghỉ Ốm', 'SICK', 1, 30, 'Nghỉ ốm có giấy bác sĩ', now, now);
  db.prepare(`INSERT INTO leaveTypes (id, name, code, paidLeave, maxDaysPerYear, description, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`).run(leaveMaternityId, 'Nghỉ Thai Sản', 'MATERNITY', 1, 180, 'Nghỉ thai sản theo quy định', now, now);
  db.prepare(`INSERT INTO allowances (id, name, code, amount, isTaxable, description, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`).run(uuidv4(), 'Phụ Cấp Ăn Trưa', 'LUNCH', 730000, 0, 'Phụ cấp ăn trưa hàng tháng', now, now);
  db.prepare(`INSERT INTO allowances (id, name, code, amount, isTaxable, description, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`).run(uuidv4(), 'Phụ Cấp Xăng Xe', 'TRANSPORT', 500000, 0, 'Phụ cấp xăng xe đi lại', now, now);
  db.prepare(`INSERT INTO allowances (id, name, code, amount, isTaxable, description, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`).run(uuidv4(), 'Phụ Cấp Điện Thoại', 'PHONE', 300000, 1, 'Phụ cấp liên lạc điện thoại', now, now);
  db.prepare(`INSERT INTO allowances (id, name, code, amount, isTaxable, description, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`).run(uuidv4(), 'Phụ Cấp Nhà Ở', 'HOUSING', 1000000, 1, 'Phụ cấp hỗ trợ nhà ở', now, now);
  db.prepare(`INSERT INTO holidays (id, name, date, year, isPaid, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?)`).run(uuidv4(), 'Tết Dương Lịch', '2026-01-01', 2026, 1, now, now);
  db.prepare(`INSERT INTO holidays (id, name, date, year, isPaid, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?)`).run(uuidv4(), 'Tết Nguyên Đán', '2026-01-29', 2026, 1, now, now);
  db.prepare(`INSERT INTO holidays (id, name, date, year, isPaid, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?)`).run(uuidv4(), 'Tết Nguyên Đán', '2026-01-30', 2026, 1, now, now);
  db.prepare(`INSERT INTO holidays (id, name, date, year, isPaid, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?)`).run(uuidv4(), 'Tết Nguyên Đán', '2026-01-31', 2026, 1, now, now);
  db.prepare(`INSERT INTO holidays (id, name, date, year, isPaid, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?)`).run(uuidv4(), 'Tết Nguyên Đán', '2026-02-01', 2026, 1, now, now);
  db.prepare(`INSERT INTO holidays (id, name, date, year, isPaid, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?)`).run(uuidv4(), 'Tết Nguyên Đán', '2026-02-02', 2026, 1, now, now);
  db.prepare(`INSERT INTO holidays (id, name, date, year, isPaid, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?)`).run(uuidv4(), 'Giỗ Tổ Hùng Vương', '2026-04-06', 2026, 1, now, now);
  db.prepare(`INSERT INTO holidays (id, name, date, year, isPaid, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?)`).run(uuidv4(), 'Ngày Giải Phóng', '2026-04-30', 2026, 1, now, now);
  db.prepare(`INSERT INTO holidays (id, name, date, year, isPaid, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?)`).run(uuidv4(), 'Ngày Quốc Tế Lao Động', '2026-05-01', 2026, 1, now, now);
  db.prepare(`INSERT INTO holidays (id, name, date, year, isPaid, createdAt, updatedAt) VALUES (?, ?, ?, ?, ?, ?, ?)`).run(uuidv4(), 'Quốc Khánh', '2026-09-02', 2026, 1, now, now);
  console.log('Khởi Tạo Dữ Liệu Mẫu Thành Công!');
  console.log('Tài Khoản Đăng Nhập:');
  console.log('- HRRO: minh.nguyen@company.com / password123');
  console.log('- Manager: duc.le@company.com / password123');
  console.log('- Employee: an.pham@company.com / password123');
};
seedData();